# Generated by Django 3.2 on 2021-06-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pseudonym', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(max_length=255, null=True)),
                ('biography', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/artist')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('artists', models.ManyToManyField(related_name='tracks', to='music.Artist')),
                ('genre', models.ManyToManyField(related_name='tracks', to='music.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/release')),
                ('tracks', models.ManyToManyField(related_name='release', to='music.Track')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tracks', models.ManyToManyField(related_name='playlists', to='music.Track')),
            ],
        ),
    ]
