# Generated by Django 3.2 on 2021-06-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='imageURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
