# Generated by Django 3.2 on 2021-05-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20210509_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='release',
        ),
        migrations.AddField(
            model_name='release',
            name='tracks',
            field=models.ManyToManyField(to='music.Track'),
        ),
    ]
