# Generated by Django 3.2 on 2021-05-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20210509_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='isSingle',
        ),
        migrations.AddField(
            model_name='playlists',
            name='tracks',
            field=models.ManyToManyField(related_name='playlists', to='music.Track'),
        ),
        migrations.AlterField(
            model_name='release',
            name='tracks',
            field=models.ManyToManyField(related_name='release', to='music.Track'),
        ),
        migrations.AlterField(
            model_name='track',
            name='artists',
            field=models.ManyToManyField(related_name='tracks', to='music.Artist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.ManyToManyField(related_name='tracks', to='music.Genres'),
        ),
    ]
