# Generated by Django 3.2 on 2021-05-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20210509_1809'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
        migrations.RenameModel(
            old_name='Playlists',
            new_name='Playlist',
        ),
        migrations.AlterField(
            model_name='artist',
            name='pseudonym',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
