# Generated by Django 3.2 on 2021-05-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20210509_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, upload_to='img/artist'),
        ),
        migrations.AddField(
            model_name='release',
            name='poster',
            field=models.ImageField(blank=True, upload_to='img/release'),
        ),
    ]
