# Generated by Django 3.2 on 2021-06-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_release_issingle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='isSingle',
        ),
        migrations.AddField(
            model_name='artist',
            name='biography',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='strMusicBrainzArtistID',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='strMusicBrainzAlbumID',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='strMusicBrainzTrackID',
            field=models.TextField(null=True),
        ),
    ]
